### ISSUE TITLE
Invincible balloon spawns

### ISSUE THREAD

**Issue by 1920049** [nickc01/Corrupted-Kin#1]
Some of the balloon spawns behave normally, but some others are not possible to kill. Using debug mod, it seems that the invincible ones spawn with -22 hp, whereas the normal ones spawn with 10. A few other people have come across this issue, and it seems to be only on the most recent version.

Sorry if this isn't the right place to put this, I'm not very familiar with this website.

**Comment by nickc01** [comment]
Ill take a look when i have a chance. It sounds like some part of the Object Pooling system is crashing somewhere, preventing the reused balloons from having their health properly reset. Do you have a Modlog.txt or Player.log from around the time of the bug occuring? You can find both files at "C:\Users\USERNAMEHERE\AppData\LocalLow\Team Cherry\Hollow Knight".

**Comment by 1920049** [comment]
Here: [ModLog.txt](https://github.com/nickc01/Corrupted-Kin/files/14235337/ModLog.txt)

Your theory seems to make sense, as when I play the fight without strength equipped some of the balloons spawn with -11 hp rather than -22.

**Comment by nickc01** [comment]
> Here: [ModLog.txt](https://github.com/nickc01/Corrupted-Kin/files/14235337/ModLog.txt)
> 
> Your theory seems to make sense, as when I play the fight without strength equipped some of the balloons spawn with -11 hp rather than -22.

Just got the issue fixed. Ideally, when the balloons get hit for the final time, they have an OnDeath() function that is called to make them stop their usual movement and to make them disappear. However, when the balloon got recycled, the OnDeath() function wasn't getting called, leading to invincible balloons. I just got this fixed, and should be release sometime soon.
